baseurl = "https://monicalent.com/"
title = "Monica Lent"
theme = "pickles"
languageCode = "en-us"
copyright = "&copy; Monica Lent 2019"
paginate = 5
paginatePath = "page"
enableEmoji = true

[Author]
    name = "Monica"
    profile = "https://monicalent.com"

[Taxonomies]
    tag = "tags"

[Params]
    headline = "Monica Lent"
    description = "Software engineer based in Berlin, specializing in ReactJS, NodeJS, design systems, and scalable frontend architecture."
    subtitle = "Software engineer based in Berlin"
    logo = "favicon.png"
    favicon = "favicon.png"
    github = "mlent"
    gplus = "https://google.com/+MonicaLent"
    twitter = "monicalent"
    ga_api_key = "UA-40399378-2"
    avatar = "/images/photo.jpg"
    author = "Monica Lent"
    authorwebsite = "http://monicalent.com"
    bio = "Software engineer based in Berlin"
    contact = "lent.monica@gmail.com"
    linkedin = "monica-lent-542122145"

[Permalinks]
    blog = "/:section/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Speaking"
    url = "/speaking"
    weight = 3

[[menu.main]]
    name = "Writing"
    url = "/blog"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5
